import {test} from 'node:test';
import assert from 'node:assert/strict';
import {phaseFor,integrateVelocity,reserve,advanceFeeding,captureLight,nextMeal,steeringRate,SPAWN_DISTANCE,SPAWN_INTERVAL,MAX_WISPS,JET_DISTANCE} from '../src/simulation.js';
test('progression crosses each boundary exactly',()=>{assert.deepEqual([0,1,7,8,74,75,349,350].map(phaseFor),['first-light','awakening','awakening','nebula','nebula','star','star','singularity']);});
test('two arms cannot own or consume the same wisp',()=>{const w={owner:null,eaten:false};const a={index:0,target:null},b={index:1,target:null};assert.ok(reserve(a,w));assert.equal(reserve(b,w),false);assert.equal(advanceFeeding(a,.5),null);assert.equal(w.eaten,false);assert.equal(advanceFeeding(a,a.mealDuration/1.5-.5),w);assert.equal(w.eaten,true);assert.equal(advanceFeeding(a,1),null);assert.equal(reserve(b,w),false);});
test('water drag slows glide independently of frame rate',()=>{let a=[5,0,0],b=[5,0,0];for(let i=0;i<30;i++)a=integrateVelocity(a,[0,0,0],1/60);for(let i=0;i<60;i++)b=integrateVelocity(b,[0,0,0],1/120);assert.ok(Math.abs(a[0]-b[0])<1e-10);assert.ok(a[0]<.2&&a[0]>.1);for(let i=0;i<60;i++)a=integrateVelocity(a,[0,0,0],1/60);assert.deepEqual(a,[0,0,0]);});
test('jet input is bounded and can move on all three axes',()=>{const v=integrateVelocity([0,0,0],[1,1,1],.016,20);assert.ok(v.every(x=>x>0));assert.ok(Math.hypot(...v)<=10.000001);});
test('dash exceeds ordinary speed and retains momentum during the burst',()=>{const dash=integrateVelocity([0,0,-21],[0,0,0],.5,0,true),swim=integrateVelocity([0,0,-21],[0,0,0],.5);assert.ok(Math.hypot(...dash)>18);assert.ok(Math.hypot(...swim)<=10);});
test('mouse steering has a stable center and symmetric bounded turn rates',()=>{assert.equal(steeringRate(.1),0);assert.equal(steeringRate(-.1),0);assert.equal(steeringRate(.8),-steeringRate(-.8));assert.ok(steeringRate(.8)>steeringRate(.3));assert.equal(steeringRate(2),steeringRate(1));});
test('light fields require travel and limit density',()=>{assert.equal(SPAWN_DISTANCE,JET_DISTANCE*3);assert.ok(SPAWN_INTERVAL>=20);assert.ok(MAX_WISPS<=12);});
test('turn rate is twenty percent faster',()=>{assert.ok(Math.abs(steeringRate(1)-1.15*1.2)<1e-12);});
test('more than eight captures stay owned and are eaten exactly once',()=>{const arms=Array.from({length:8},(_,index)=>({index,target:null,cargo:[]})),lights=Array.from({length:12},()=>({owner:null,eaten:false}));for(const w of lights)assert.ok(captureLight(arms,w));assert.equal(captureLight(arms,lights[0]),null);assert.ok(arms.every(a=>a.target));let eaten=0;for(const a of arms){while(a.target){assert.ok(advanceFeeding(a,3.21));eaten++;nextMeal(a);}}assert.equal(eaten,12);assert.ok(lights.every(w=>w.eaten));});
test('interrupted meals retain their light and progress until still long enough',()=>{const a={index:0,target:null},w={owner:null,eaten:false};reserve(a,w);assert.equal(advanceFeeding(a,.5),null);assert.equal(advanceFeeding(a,20,false),null);assert.equal(a.elapsed,.5*1.5*3.2/a.mealDuration);assert.ok(a.mealDuration>=1&&a.mealDuration<=2);assert.equal(a.target,w);assert.equal(w.eaten,false);assert.equal(advanceFeeding(a,a.mealDuration-.5),w);});


