import * as T from 'three';
import {createKali} from './creature.js';
import {createGripSimulation,armRadius} from './grip-physics.js';
import {sampleSoftArm} from './soft-arm.js';
const $=s=>document.querySelector(s),scene=new T.Scene();scene.background=new T.Color(0x030711);scene.fog=new T.FogExp2(0x030711,.022);
const renderer=new T.WebGLRenderer({canvas:$('#lab'),antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.4));renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=.8;
const camera=new T.PerspectiveCamera(43,innerWidth/innerHeight,.1,100);camera.position.set(8,-4.7,11.5);
const orbit={yaw:.57,pitch:-.18,distance:14.5},target=new T.Vector3(.8,-1.65,0),pointers=new Map();
const controls={update(){camera.position.set(Math.sin(orbit.yaw)*Math.cos(orbit.pitch),Math.sin(orbit.pitch),Math.cos(orbit.yaw)*Math.cos(orbit.pitch)).multiplyScalar(orbit.distance).add(target);camera.lookAt(target);}};
const canvas=renderer.domElement;
canvas.addEventListener('pointerdown',e=>{canvas.setPointerCapture(e.pointerId);pointers.set(e.pointerId,[e.clientX,e.clientY]);});
canvas.addEventListener('pointermove',e=>{const previous=pointers.get(e.pointerId);if(!previous)return;const before=[...pointers.values()];pointers.set(e.pointerId,[e.clientX,e.clientY]);if(pointers.size===1){orbit.yaw-=(e.clientX-previous[0])*.006;orbit.pitch=Math.max(-1.4,Math.min(1.4,orbit.pitch+(e.clientY-previous[1])*.006));}else{const after=[...pointers.values()],d0=Math.hypot(before[0][0]-before[1][0],before[0][1]-before[1][1]),d1=Math.hypot(after[0][0]-after[1][0],after[0][1]-after[1][1]);if(d1>1)orbit.distance=Math.max(5,Math.min(24,orbit.distance*d0/d1));}});
for(const event of ['pointerup','pointercancel','lostpointercapture'])canvas.addEventListener(event,e=>pointers.delete(e.pointerId));
canvas.addEventListener('wheel',e=>{e.preventDefault();orbit.distance=Math.max(5,Math.min(24,orbit.distance*Math.exp(e.deltaY*.001)));},{passive:false});
scene.add(new T.HemisphereLight(0x86a9de,0x071024,1.2));for(const [x,y,z,color,power] of [[4,5,6,0xb3dfff,80],[-5,0,-4,0x756bd3,95],[0,-5,5,0x78b9ed,35]]){const l=new T.PointLight(color,power,25,2);l.position.set(x,y,z);scene.add(l);}
const kali=createKali();scene.add(kali.group);const sim=createGripSimulation({exploration:true});
for(const arm of kali.arms){
 arm.radiusProvider=u=>armRadius(u)*(sim.state.arms[arm.index].radiusScale||1);
 arm.poseProvider=points=>sampleSoftArm(sim.state.arms[arm.index].points,points,(p,u)=>{
  if(u<.12)return;const b=sim.state.ball,d=p.map((v,k)=>v-b.p[k]),length=Math.hypot(...d),minimum=b.radius+arm.radiusProvider(u);
  if(length<minimum&&length>1e-8)for(let k=0;k<3;k++)p[k]=b.p[k]+d[k]*minimum/length;
 });
}
const paint=document.createElement('canvas');paint.width=1024;paint.height=512;const ctx=paint.getContext('2d');ctx.fillStyle='#08090e';ctx.fillRect(0,0,1024,512);for(const x of [256,768]){ctx.fillStyle='#eee7d9';ctx.beginPath();ctx.ellipse(x,256,110,108,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#101018';ctx.font='bold 160px Georgia';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText('8',x,264);}const texture=new T.CanvasTexture(paint);texture.colorSpace=T.SRGBColorSpace;
const ball=new T.Mesh(new T.SphereGeometry(sim.state.ball.radius,64,40),new T.MeshPhysicalMaterial({map:texture,roughness:.17,metalness:0,clearcoat:1,clearcoatRoughness:.08}));scene.add(ball);
const field=new T.Mesh(new T.SphereGeometry(1,40,28),new T.ShaderMaterial({transparent:true,depthWrite:false,blending:T.AdditiveBlending,uniforms:{power:{value:0},time:{value:0}},vertexShader:'varying vec3 n;varying vec3 eye;varying vec3 p;void main(){p=position;n=normalize(normalMatrix*normal);vec4 v=modelViewMatrix*vec4(position,1.);eye=-v.xyz;gl_Position=projectionMatrix*v;}',fragmentShader:'uniform float power;uniform float time;varying vec3 n;varying vec3 eye;varying vec3 p;void main(){float rim=pow(1.-abs(dot(normalize(n),normalize(eye))),3.);float vein=pow(.5+.5*sin(p.y*25.+sin(p.x*12.)+time*2.),14.);gl_FragColor=vec4(vec3(.38,.15,.95)*(rim+vein*.25)*power,(rim*.35+vein*.03)*power);}' }));scene.add(field);
const forceData=new Float32Array(8*25*6),forceGeometry=new T.BufferGeometry();forceGeometry.setAttribute('position',new T.BufferAttribute(forceData,3).setUsage(T.DynamicDrawUsage));const vectors=new T.LineSegments(forceGeometry,new T.LineBasicMaterial({color:0xd18bff,transparent:true,opacity:.55,depthTest:false}));vectors.frustumCulled=false;scene.add(vectors);
const dots=new T.InstancedMesh(new T.SphereGeometry(.024,8,6),new T.MeshBasicMaterial({color:0xe3c1ff,depthTest:false}),200);dots.frustumCulled=false;scene.add(dots);const dummy=new T.Object3D();
let paused=false,last=performance.now(),maxLoad=1,smoothedLoad=0,smoothedNet=0;
for(let i=0;i<8;i++)$('#arm-loads').appendChild(document.createElement('i'));
$('#grip').onclick=()=>{sim.grip();$('#status').textContent='Reaching → contact → opposing pressure.';};$('#release').onclick=()=>{sim.release();$('#status').textContent='Relaxing the muscles. Contact forces fall as the arms withdraw.';};$('#squeeze').oninput=e=>{sim.state.squeeze=Number(e.target.value)/100;$('#drive').value=e.target.value+'%';};$('#nudge').onclick=()=>{sim.nudge([1,0,0],1.7);$('#status').textContent='Lateral disturbance applied. Watch the ball and opposing contact loads.';};$('#unbalance').onclick=()=>{sim.state.enabled[0]=!sim.state.enabled[0];$('#unbalance').textContent=sim.state.enabled[0]?'Release one arm':'Restore arm';};$('#pause').onclick=()=>{paused=!paused;$('#pause').textContent=paused?'Continue':'Pause';};$('#reset').onclick=()=>{sim.reset();smoothedLoad=smoothedNet=0;$('#unbalance').textContent='Release one arm';$('#status').textContent='Ready. Grasp the ball to establish contact.';};window.addEventListener('keydown',e=>{if(e.code==='Space'&&!e.repeat&&e.target.tagName!=='INPUT'&&e.target.tagName!=='BUTTON'){e.preventDefault();sim.state.command?$('#release').click():$('#grip').click();}});
function resize(){camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);}window.addEventListener('resize',resize);resize();
function frame(now){requestAnimationFrame(frame);const dt=Math.max(0,Math.min(.05,(now-last)/1000));last=now;if(!paused)sim.update(dt);const s=sim.state;kali.update(s.time,paused?0:dt,4,0,0);kali.core.visible=false;kali.light.intensity=0;ball.position.set(...s.ball.p);field.visible=$('#field').checked;field.position.copy(ball.position);field.scale.setScalar(s.ball.radius*(1.035+.045*s.activation));field.material.uniforms.power.value=Math.min(1,s.load/1600);field.material.uniforms.time.value=s.time;
let count=0;for(const c of s.contacts){if(c.force<.5||c.section%3!==0)continue;const p=c.point,n=c.normal,scale=.08+Math.min(.5,c.force*.014);forceData.set([...p,...p.map((v,k)=>v-n[k]*scale)],count*6);dummy.position.set(...p);dummy.updateMatrix();dots.setMatrixAt(count,dummy.matrix);count++;}forceGeometry.setDrawRange(0,count*2);forceGeometry.attributes.position.needsUpdate=true;dots.count=count;dots.instanceMatrix.needsUpdate=true;vectors.visible=dots.visible=$('#forces').checked;
smoothedLoad+=(s.load-smoothedLoad)*(1-Math.exp(-dt*6));smoothedNet+=(Math.hypot(...s.netForce)-smoothedNet)*(1-Math.exp(-dt*6));$('#load').textContent=smoothedLoad.toFixed(0);$('#net').textContent=smoothedNet.toFixed(1);$('#contacts').textContent=s.perArm.filter(f=>f>1).length+' / 8';$('#stretch').textContent=(s.maxStretch*100).toFixed(1)+'%';maxLoad=Math.max(120,...s.perArm);for(let i=0;i<8;i++)$('#arm-loads').children[i].style.height=(3+Math.min(1,s.perArm[i]/maxLoad)*40)+'px';controls.update();renderer.render(scene,camera);}
requestAnimationFrame(frame);window.gripLab={get state(){return JSON.parse(JSON.stringify(sim.state));}};
