export const NARRATION={
 confrontation:'You dare destroy my light!?',
 discovery:"Now, what is this?",
 firstMeal:"It's so warm.",
 opening:'She had existed in a timeless void, untouched by the light...',
 sweetness:'Within the light, she tasted a delectable sweetness.',
 first:'Approach the lonely blue ember.',
 warm:'It’s so… warm.',
 hunger:'I should like another.',
 secondMeal:'Mmm, delicious.',
 gathering:'As she devoured more light,',
 nebula:'a nebula began to swirl within her.',
 ignition:'And in the endless dark, a star was born.',
 star:'Keep feeding. Even a star has a limit.',
 giant:'A blue supergiant. A heart made of stolen light.',
 hungered:'Still, she hungered.',
 escape:'Until even light could no longer escape.',
 darkness:'And within her… unfathomable darkness.',
 ending:'The darkness has a hunger. Even a star could not be enough',
 singularity:'Feed the newborn singularity. Every swallowed star makes it grow.'
};
